apiVersion: v1
entries:
  id-vault:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-11-10T19:01:55.4130273Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: ed88b7f0287896db9154be4ce08187a15171648c607958a59974bf6072519ca5
    home: www.id-vault.com
    icon: www.id-vault.com
    name: id-vault
    urls:
    - id-vault-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-10T19:01:55.4069615Z"
